apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: gcr.io/brave-monitor-432315-q6/ui-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
spec:
  type: LoadBalancer
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
